{{- range .Values.clusterIssuers }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .config.name }}
  namespace: cert-manager
spec:
  acme:
    server: {{ .config.server }}
    email: {{ .config.email }}
    privateKeySecretRef:
      name: {{ .config.name }}
    solvers:
    - dns01:
        {{- if eq .type "clouddns" }}
        clouddns:
          project: {{ .config.projectId }}
          serviceAccountSecretRef:
            key: {{ .config.serviceAccountSecretRef.key }}
            name: {{ .config.serviceAccountSecretRef.name }}
        {{- else if eq .type "route53" }}
        route53:
          region: {{ .config.region }}
          accessKeyId: {{ .config.accessKeyId }}
          secretAccessKeySecretRef:
            key: {{ .config.secretAccessKeySecretRef.key }}
            name: {{ .config.secretAccessKeySecretRef.name }}
        {{- end }}

---
{{- end }}
