{{- range .Values.clusterIssuers }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .config.name }}
  namespace: cert-manager
spec:
  acme:
    server: {{ .config.server }}
    email: {{ .config.email }}
    privateKeySecretRef:
      name: {{ .config.name }}
    solvers:
    - dns01:
        {{- if eq .type "clouddns" }}
        clouddns:
          project: {{ .config.projectId }}
          serviceAccountSecretRef:
            key: {{ .config.serviceAccountSecretRef.key }}
            name: {{ .config.serviceAccountSecretRef.name }}
        {{- else if eq .type "route53" }}
        route53:
          region: {{ .config.region }}
          accessKeyID: {{ .config.accessKeyID }}
          secretAccessKeySecretRef:
            key: {{ .config.secretAccessKeySecretRef.key }}
            name: {{ .config.secretAccessKeySecretRef.name }}
        {{- else if eq .type "cloudflare" }}
        cloudflare:
          email: {{ .config.email }}
          apiKeySecretRef:
            name: {{ .config.apiKeySecretRef.name }}
            key: {{ .config.apiKeySecretRef.key }}
        {{- end }}
      {{- if .domains }}
      selector:
        dnsZones:
        {{- range .domains }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}

---
{{- end }}
