{{ $apiVersion := .Values.apiVersion }}
{{- range .Values.clusterIssuers }}
apiVersion: {{ $apiVersion }}
kind: ClusterIssuer
metadata:
  name: {{ .config.name }}
  namespace: cert-manager
spec:
{{- if eq .type "selfsigned" }}
  selfSigned: {}
{{- else }}
  acme:
    server: {{ .config.server }}
    email: {{ .config.email }}
    privateKeySecretRef:
      name: {{ .config.name }}
    solvers:
    - dns01:
        {{- if eq .type "clouddns" }}
        clouddns:
          project: {{ .config.projectId }}
          {{- if hasKey .config "serviceAccountSecretRef" }}
          serviceAccountSecretRef:
            key: {{ .config.serviceAccountSecretRef.key }}
            name: {{ .config.serviceAccountSecretRef.name }}
          {{- end }}
        {{- else if eq .type "route53" }}
        route53:
          region: {{ .config.region }}
          accessKeyID: {{ .config.accessKeyID }}
          secretAccessKeySecretRef:
            key: {{ .config.secretAccessKeySecretRef.key }}
            name: {{ .config.secretAccessKeySecretRef.name }}
        {{- else if eq .type "cloudflare" }}
        cloudflare:
          email: {{ .config.email }}
          {{- with .config.apiKeySecretRef }}
          apiKeySecretRef:
            name: {{ .name }}
            key: {{ .key }}
          {{- end }}
          {{- with .config.apiTokenSecretRef }}
          apiTokenSecretRef:
            name: {{ .name }}
            key: {{ .key }}
          {{- end }}
        {{- end }}
      {{- if .domains }}
      selector:
        dnsZones:
        {{- range .domains }}
        - {{ . | quote }}
        {{- end }}
      {{- end }}
{{- end }}
---
{{- end }}
