{{- range .clusterissuers }}
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ .projectId }}-{{ .name }}
  namespace: cert-manager
spec:
  acme:
    server: {{ .server }}
    email: {{ .email }}
    privateKeySecretRef:
      name: {{ .name }}
    solvers:
    - dns01:
        clouddns:
          project: {{ .projectId }}
          serviceAccountSecretRef:
            key: {{ .serviceAccountSecretRef.key }}
            name: {{ .serviceAccountSecretRef.name }}
---
{{- end }}
