{{- $name := include "ingresses.fullname" . -}}
{{- range .Values.ingresses }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations: |
{{ toYaml .annotations | indent 4 }}
  labels: |
{{ toYaml .labels | indent 4 }}
  name: {{ .name }}
spec:
  rules:
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: {{ .serviceName }}
          servicePort: {{ .servicePort }}
        path: /
{{- with .tls }}
  tls:
  - hosts:
    - {{ .host }}
    secretName: "tls-{{ $name }}"
{{- end }}
---
{{- end }}
