{{- $name := include "ingresses.fullname" . -}}
{{- range .Values.ingresses }}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
{{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  rules:
  - host: {{ .host }}
    http:
      paths:
      - backend:
          serviceName: {{ .serviceName }}
          servicePort: {{ .servicePort }}
        path: /
{{- with .tls }}
  tls:
  - hosts:
    - {{ .host }}
    secretName: "tls-{{ $name }}"
{{- end }}
---
{{- end }}
