{{- $name := include "ingresses.fullname" . -}}
{{- range .Values.services }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
{{- with .annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with .labels }}
  labels:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- with .ports }}
  ports:
{{ toYaml . | indent 4}}
{{- end }}
{{- with .selector }}
  selector:
{{ toYaml . | indent 4}}
{{- end }}
  type: ClusterIP
---
{{- end }}
